### ISSUE TITLE
[ `Backend` ] : Redesign `404`, `500`, `403`, `400` page

### ISSUE THREAD

**Issue by baseplate-admin** [coreproject-moe/CoreProject#3431]
Rewrite that in svelte and change the designs a bit

**Comment by AKindWorld** [comment]
I'm back, with new simple design(s). Will be adding designs for more pages (404, 403 and 400), and am working on some stickers art.

Simple mockup preview:
![Error Page 500](https://github.com/coreproject-moe/CoreProject-Monorepo/assets/41228366/0d5b6b12-0cae-45c8-81bd-348005753afd)

wish you a good time!

**Comment by baseplate-admin** [comment]
.........

@tokitouq, see i told you @AKindWorld  was back

**Comment by baseplate-admin** [comment]
@AKindWorld do you have figma file?

**Comment by tokitouq** [comment]
> @AKindWorld do you have figma file?

Its on main project file.
https://www.figma.com/file/tNUUtsk20ltOrQICdEoggG/Core-Project?type=design&node-id=4152-5831&mode=design&t=zLl9g7AhHFh3UeSS-4

**Comment by baseplate-admin** [comment]
@tokitouq, if you are to implement the pages remember :

* No Tailwind
* No Svelte

Because these pages can be shown when `vite` is not working or has a problem. So thats why just `<style></style>` tag to design everything here.


---

As for @AKindWorld, is the `500` a image or a font with some magix?

**Comment by AKindWorld** [comment]
> As for @AKindWorld, is the 500 a image or a font with some magix?

It's actually font work, but sliced up for the effect- so we can export and use it as an SVG in the actual code. Lemme know if you need the exported SVG file (it's the layer named "500 TEXT [for SVG export]").

**Comment by tokitouq** [comment]
> Lemme know if you need the exported SVG file (it's the layer named "500 TEXT [for SVG export]").

@AKindWorld Yes, I saw that. Also do you mind granting me edit permission (not to edit, but just in case)?.
I've already send you a request for that.

**Comment by AKindWorld** [comment]
>Also do you mind granting me edit permission (not to edit, but just in case)? I've already send you a request for that.

@tokitouq Yup, approved.
