### ISSUE TITLE
Increase brightness/custom patch panel

### ISSUE THREAD

**Issue by baseplate-admin** [coreproject-moe/CoreProject#3658]
<img src="https://github.com/coreproject-moe/CoreProject-Monorepo/assets/61817579/8b4163d5-ed7a-487f-b8ff-555363a516ac" />

This section looks a bit dark, can we make it look shiny?

Something like 
![image](https://github.com/coreproject-moe/CoreProject-Monorepo/assets/61817579/8da84953-cecb-415b-9cd1-5d9a8b5d8945)

from https://nextjs.org/docs looks cool

cc:
@AKindWorld 
@tokitouq

**Comment by baseplate-admin** [comment]
Another good site : https://opensauced.pizza/

**Comment by baseplate-admin** [comment]
![image](https://github.com/coreproject-moe/CoreProject-Monorepo/assets/61817579/25cc9ef2-ecd4-4274-9af8-03e632d48d04)

![image](https://github.com/coreproject-moe/CoreProject-Monorepo/assets/61817579/9a4f6226-d2da-4b55-817b-37ac5fe5c0b5)

**Comment by moonlitgrace** [comment]
Seems fixed on V3 design :smiley:
